root: true
env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
reportUnusedDisableDirectives: true
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
      ignoreRestSiblings: true
