name: Continuous Delivery

on:
  pull_request:
    branches:
      - master

jobs:
  Continuous_Delivery:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up sources
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Set up TEST env
        run: |
          echo "NODE_ENV=production" > .env
          echo "DB_ROOT_PASSWORD=root" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SALT_ROUND=${{ secrets.SALT_ROUND }}" >> .env

      - name: Set up DB
        run: |
          sudo service mysql start
          mysql --user=root --password=root --execute="CREATE DATABASE a_todo CHARACTER SET utf8;"
          yarn db:migrate

      - name: Test
        run: yarn test

      - name: Login to docker-hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up PRODUCTION env
        run: |
          echo "NODE_ENV=production" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SALT_ROUND=${{ secrets.SALT_ROUND }}" >> .env

      - name: Build docker image
        run: yarn build

      - name: Push to docker-hub
        run: yarn docker:push
