name: test and build

on:
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn --frozen-lockfile

      - name: create .env (local TEST)
        run: |
          touch .env
          echo "NODE_ENV=production" >> .env
          echo "DB_ROOT_PASSWORD=root" >> .env
          echo "DEBUG=${{ vars.DEBUG }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "" >> .env
      - run: sudo service mysql start
      - run: mysql --user=root --password=root --execute="CREATE DATABASE a_todo;"
      - run: yarn db:migrate
      - run: yarn test

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create .env (real PRODUCTION)
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "" >> .env
      - run: yarn build
